### ISSUE TITLE
Operator (OLM) 1.4 fails installing on Openshift - webhook failed to update certificate from disk

### ISSUE THREAD

**Issue by dan1el-k** [jetstack/cert-manager-olm#33]
So far we were using the operator 1.1 from the redhat certified operator catalog, but as we encountered dfferences with the expiry date of CertManager and the real expiry of the certificate (checked via openssl), we thought it would be good to update to the latest image (in hope this was fixed).
So, we tried to install the operator 1.4 via the Openshift Operator catalouge (OLM) - from the community operators.
1st difference is, that there is not operator instance CR needed, but all the available objects are 2-3 times listes in the OLM overview (seems to be another bug of the operator)
The operator container gets deployed, and spinns up 3 additional containers:
cert-manager
cert-manager-cainjector
cert-manager-webhook

the webhook pod gets never healthy, as it fails with the error listed below.
We retried it on another cluster as well, but same behaviour.
Was tested on Openshift OKD 4.6

**Describe the bug**:

cert-manager-webhook pod fails to get healthy.
```
E0809 20:47:26.508937       1 file_source.go:101] cert-manager/webhook "msg"="failed to update certificate from disk" "error"="failed to read keyPath: open /tmp/k8s-webhook-server/serving-certs/tls.key: no such file or directory"  "failures"=3
I0809 20:47:29.707969       1 server.go:408] cert-manager/webhook "msg"="Health check failed as CertificateSource is unhealthy"
```

**Expected behaviour**:
Sucessfull deployment of CertManager operator from community operator catalog

**Steps to reproduce the bug**:
In the Openshift operator catalog, select community-operators and click install of certManager 1.4 for all namespaces

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version: Openshift OKD 4.6
- Cloud-provider/provisioner: AWS
- cert-manager version: 1.4
- Install method: Operator OLM

**Comment by dan1el-k** [comment]
I have found the problem in the code:

https://github.com/jetstack/cert-manager-olm/blob/471685559b7d753527006e731cee6bb7f72d927c/github.com/operator-framework/community-operators/1.4.3/manifests/cert-manager.clusterserviceversion.yaml#L680-L681

`                - --tls-cert-file=/tmp/k8s-webhook-server/serving-certs/tls.crt
                - --tls-private-key-file=/tmp/k8s-webhook-server/serving-certs/tls.key`
according to this site:
https://olm.operatorframework.io/docs/advanced-tasks/adding-admission-and-conversion-webhooks/
, for backword compatibilty following should use instead:

**Comment by wallrj** [comment]
@dan1el-k @timroster @miminar Apologies for not replying sooner.

I'm really struggling to create an OpenShift 4.6 cluster to recreate this. CRC 1.22 gives me a 4.6 cluster where the community-operators catalog is broken: 
 * https://github.com/code-ready/crc/issues/2827

I have however checked that the cert-manager community-operator works in OpenShift 4.7, 4.8, and 4.9.
Because those newer versions do mount the  `/tmp/k8s-webhook-server/serving-certs/` directory.

And I've checked that the backwards compatible path is still mounted in OpenShift 4.9, it appears that it is.

![image](https://user-images.githubusercontent.com/978965/140331756-26df58cf-00ff-422c-aab9-338c22dd4f72.png)


So it should be safe for me to change the mount path, as you suggested, and the community-bundle should then work with 4.6,4.7,4.8 and 4.9

I will try and make this change before the next community-operators release.
